version: '3.4'

services:
  whoare:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    environment:
      ENV: dev
    ports:
      - $REST_PORT:8080
    volumes:
      - .:/go/src/
    networks:
      - whoare
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

networks:
  whoare:
    driver: bridge
