apiVersion: v1
kind: Service
metadata:
  name: whoare
  labels:
    app: whoare
    service: whoare
spec:
  type: ClusterIP
  selector:
    app: whoare
  ports:
  - name: http
    port: 8080
    targetPort: 8080
