FROM golang:1.17-alpine AS builder

ENV PATH="/go/bin:${PATH}"
ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

WORKDIR /go/src

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go build -o main .

FROM scratch AS runner

COPY --from=builder /go/src/main /

EXPOSE 8080

ENTRYPOINT ["./main"]
